name: Check

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: make check
    - name: Run
      run: make run

